version: '3.5'

services:
  app:
    image: moviendome/react-native-example:latest
    tty: true
    stdin_open: true
    user: root
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV= development
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_ADDRESS}
    ports:
      - 3000:3000
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    command: >
      /bin/bash -c "yarn install && expo start${PLATFORM}"
